version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install

  pre_build:
    commands:
      - echo Pre-build phase...

  build:
    commands:
      - npm run build
      - mkdir -p ea-test-application/BuildArtif
      - mv path_to_generated_files/* ea-test-application/BuildArtif

  post_build:
    commands:
      - echo Post build phase...

artifacts:
  files:
    - ea-test-application/BuildArtif/**/*

cache:
  paths:
    - 'node_modules/**/*'
